global:
  scrape_interval: 5s # Scrape every 5 seconds

scrape_configs:
  - job_name: "transaction-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["transaction-service:8090"]
