apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ms-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: myapp.local
      http:
        paths:
          - path: /transaction-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: transaction-service
                port:
                  number: 8090

          - path: /user-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 8091

          - path: /category-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: category-service
                port:
                  number: 8092
